backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:

  - name: 'blog'
    label: 'Blog'
    folder: 'assets/content/blog'
    create: true
    format: 'json'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true}
      - { label: "Featured image", name: "thumbnail", widget: "image", required: true}
      - { label: 'Image alt tag', name: 'alt', widget: 'string', required: true}
      - { label: 'Publish date', name: 'date', widget: 'datetime', required: true }
      - { label: 'Description', name: 'description', widget: 'string', required: true }
      - { label: 'Description', name: 'description', widget: 'select', options: ["Dan", "Ellie", "Lanks", "Roisin"]}
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }


  - name: 'event'
    label: 'Event'
    folder: 'assets/content/event'
    create: true
    format: 'json'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: "Featured image", name: "thumbnail", widget: "image", required: true}
      - { label: 'Image alt tag', name: 'alt', widget: 'string', required: true}
      - { label: 'Event start date and time', name: 'eventdate', widget: 'datetime', required: true }
      - { label: 'Location', name: 'location', widget: 'string', required: true }
      - { label: 'Link to eventbrite', name: 'url', widget: 'string', required: true }
      - { label: 'Description', name: 'description', widget: 'string', required: true }
