backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    sort: "date:desc"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: Summary 80-220, name: summary, widget: text, required: true, pattern: ['.{80,220}', "Must be within 80 and 220 characters"]}
      - {label: "Publish Date", name: "date", widget: "date", required: true}
      - {label: "Author", name: "author", widget: "string", required: true}
      - {label: "Author Link", name: "authorlink", widget: "string", required: true}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: true}
      - {label: "Body", name: "body", widget: "markdown", required: true}